# Clave única del proyecto
sonar.projectKey=AngelMlt03_TFG_Game_Swap
# Organización a la que pertenece el proyecto en SonarCloud
sonar.organization=angelmlt03
# Nombre del proyecto en SonarCloud
sonar.projectName=TFG_Game_Swap

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.java.binaries=backend/target

# Codificación de los archivos fuente
sonar.sourceEncoding=UTF-8

# --- CONFIGURACIÓN DE EXCLUSIONES ---
# Evita analizar código generado o librerías externas
sonar.exclusions=**/node_modules/**, **/dist/**, **/*.spec.ts