# Clave única del proyecto
sonar.projectKey=angelmlt03_TFG_Game_Swap
# Organización a la que pertenece el proyecto en SonarCloud
sonar.organization=angelmlt03
# Nombre del proyecto en SonarCloud
sonar.projectName=TFG_Game_Swap

# Ruta a los directorios que contienen el código fuente (relativo al archivo properties)
sonar.sources=frontend/src,backend/src
sonar.tests=frontend/src,backend/src

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

sonar.java.binaries=backend/target

# Codificación de los archivos fuente
sonar.sourceEncoding=UTF-8

# --- CONFIGURACIÓN DE EXCLUSIONES ---
# Evita analizar código generado o librerías externas
sonar.exclusions=**/node_modules/**, **/dist/**, **/*.spec.ts